package pt.ulisboa.tecnico.SECDPAS;

/* these are generated by the Contract */
import SECDPAS.grpc.Contract;
import SECDPAS.grpc.DPASServiceGrpc;
import com.google.common.primitives.Bytes;
import com.google.common.primitives.Ints;
import com.google.common.primitives.Longs;
import com.google.protobuf.ByteString;
import com.google.protobuf.Empty;
import io.grpc.Metadata;
import io.grpc.Status;
import io.grpc.StatusRuntimeException;
import io.grpc.stub.StreamObserver;
import org.apache.commons.lang3.SerializationException;
import org.apache.commons.lang3.SerializationUtils;

import javax.crypto.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.security.*;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ConcurrentHashMap;

public class DPASServiceImpl extends DPASServiceGrpc.DPASServiceImplBase {

	private ConcurrentHashMap<PublicKey, ArrayList<Announcement>> privateBoard = new ConcurrentHashMap<>();
	private ArrayList<Announcement> generalBoard = new ArrayList<>();
	private ConcurrentHashMap<PublicKey, MessageHandler> clientSessions = new ConcurrentHashMap<>();
	private ConcurrentHashMap<Integer, Announcement> announcementIDs = new ConcurrentHashMap<>();

	private String databasePath;

	private PrivateKey privateKey;

	private long initialTime;
	private int announcementID = 0;

	/* for debugging change to 1 */
	private int debug = 0;

	public DPASServiceImpl(PrivateKey privateKey) throws DatabaseException{
		this.initialTime = System.currentTimeMillis();

		Path currentRelativePath = Paths.get("");
		this.databasePath = currentRelativePath.toAbsolutePath().toString() + "/src/database";
		this.privateKey = privateKey;
		load();
	}

	@Override
	public void setupConnection(Contract.DHRequest request, StreamObserver<Contract.DHResponse> responseObserver){
		if(debug != 0) System.out.println("[SETUP CONNECTION] Request from client.\n");

		byte[] encodedClientKey = request.getPublicKey().toByteArray();
		byte[] clientAgreement = request.getClientAgreement().toByteArray();
		byte[] clientFreshness = request.getFreshness().toByteArray();
		byte[] clientSignature = request.getSignature().toByteArray();

		/* TODO - freshness */
		byte[] serverFreshness = new byte[0];

		/* Obtaining the Public Key of the Client */
		PublicKey userKey = verifyPublicKey(encodedClientKey, responseObserver, encodedClientKey, clientFreshness, serverFreshness);

		if(userKey == null){
			return;
		}

		/* Message Handler for the Client */
		MessageHandler messageHandler = clientSessions.get(userKey);

		/* If it does not exist, create a new one */
		if(messageHandler == null){
			messageHandler = new MessageHandler(null);
			clientSessions.put(userKey, messageHandler);
		}

		/* TODO - DESCOMENTAR FRESHNESS */
		/* Client must be registered. Verify freshness and signature of the request */
		if(!verifyClientIsRegistered(userKey, responseObserver, encodedClientKey, clientFreshness, serverFreshness) /*|| !verifyFreshness(messageHandler, responseObserver, encodedClientKey, clientFreshness, serverFreshness)*/ || !verifySignature(Bytes.concat(encodedClientKey, clientAgreement, clientFreshness), clientSignature, userKey, responseObserver, "ClientSignatureInvalid", encodedClientKey, clientFreshness, serverFreshness)){
			return;
		}

		/* Perform server side of the agreement and add a new message handler for the current client's session */
		DiffieHellmanServer dhServer = new DiffieHellmanServer();
		byte[] serverAgreement = dhServer.execute(clientAgreement);

		SecretKey hmacKey = dhServer.getSharedHMACKey();

		messageHandler.resetSignature(hmacKey);

		/* Preparing response */
		byte[] freshness = new byte[0];
		byte[] signature = SignatureHandler.publicSign(freshness, privateKey);

		Contract.DHResponse response = Contract.DHResponse.newBuilder().setServerAgreement(ByteString.copyFrom(serverAgreement)).setFreshness(ByteString.copyFrom(freshness)).setSignature(ByteString.copyFrom(signature)).build();

		responseObserver.onNext(response);
		responseObserver.onCompleted();
	}

	@Override
	public void closeSession(Contract.CloseSessionRequest request, StreamObserver<Contract.ACK> responseObserver){
		if(debug != 0) System.out.println("[CLOSE SESSION] Request from client.\n");

		byte[] serializedPublicKey = request.getPublicKey().toByteArray();
		byte[] freshness = request.getFreshness().toByteArray();
		byte[] signature = request.getSignature().toByteArray();

		//TODO check if fresness is correct
		byte[] serverFreshness = Longs.toByteArray(new MessageHandler(null).getFreshness());

		/* Obtaining the Public Key of the Client */
		PublicKey userKey = verifyPublicKey(serializedPublicKey, responseObserver, serializedPublicKey, freshness, serverFreshness);

		if(userKey == null){
			return;
		}

		MessageHandler messageHandler = clientSessions.get(userKey);

		/* Client must be registered. Client must be in session. Verify freshness and signature of the request */
		if(!verifyClientIsRegistered(userKey, responseObserver, serializedPublicKey, freshness, serverFreshness) || !verifyIsInSession(messageHandler, responseObserver, serializedPublicKey, freshness, serverFreshness) || !verifyMessage(messageHandler, responseObserver, serializedPublicKey, signature, serializedPublicKey, freshness, serverFreshness)){
			return;
		}

		responseObserver.onNext(buildACKresponse(messageHandler, "hmac"));

		/* Closing session */
		messageHandler.resetSignature(null);

		responseObserver.onCompleted();
	}

	@Override
	public void register(Contract.RegisterRequest request, StreamObserver<Contract.ACK> responseObserver) {
		if(debug != 0) System.out.println("[REGISTER] Request from client.\n");

		byte[] encodedClientKey = request.getPublicKey().toByteArray();
		byte[] clientSignature = request.getSignature().toByteArray();

		/* Obtaining the Public Key of the Client */
		PublicKey userKey = verifyPublicKey(encodedClientKey, responseObserver, encodedClientKey, new byte[0], new byte[0]);

		if(userKey == null){
			return;
		}

		MessageHandler messageHandler = new MessageHandler(null);

		/* Client must NOT be registered. Verify freshness and signature of the request. */
		if(verifyClientIsAlreadyRegistered(userKey, responseObserver, encodedClientKey, new byte[0], new byte[0]) || !verifySignature(Bytes.concat(encodedClientKey, new byte[0]), clientSignature, userKey, responseObserver, "ClientSignatureInvalid", encodedClientKey, new byte[0], new byte[0])){
			return;
		}

		/* Registering client */
		this.privateBoard.put(userKey, new ArrayList<>());
		this.clientSessions.put(userKey, messageHandler);

		/* Saving posts */
		try{
			save("posts");
		}catch (DatabaseException e){
			System.out.println("[REGISTER] ERROR - DatabaseException -  " + e.getMessage() + "\n");
		}

		byte[] freshness = new byte[0];
		byte[] signature = SignatureHandler.publicSign(freshness, this.privateKey);

		responseObserver.onNext(Contract.ACK.newBuilder().setFreshness(ByteString.copyFrom(freshness)).setSignature(ByteString.copyFrom(signature)).build());
		responseObserver.onCompleted();
	}

	@Override
	public void post(Contract.PostRequest request, StreamObserver<Contract.ACK> responseObserver) {
		if(debug != 0) System.out.println("[SERVER] Post request from client.\n");

		/* Verify request */
		byte[] postBytes = verifyPostRequest(request, responseObserver);

		/* In case the request is faulty */
		if(postBytes == null){
			return;
		}

		PublicKey userKey = SerializationUtils.deserialize(request.getPublicKey().toByteArray());
		String[] announcements = SerializationUtils.deserialize(request.getAnnouncements().toByteArray());

		MessageHandler messageHandler = clientSessions.get(userKey);

		/* create post */
		char[] post = new String(postBytes, StandardCharsets.UTF_8).toCharArray();
		ArrayList<Announcement> announcementList = this.privateBoard.get(userKey);

		int announcementID = addCounter();
		Announcement announcement = new Announcement(post, userKey, announcements, announcementID, request.getMessageSignature().toByteArray());

		synchronized (this) {
			announcementList.add(announcement);
		}

		this.announcementIDs.put(announcementID, announcement);

		/* Save posts */
		try{
			save("posts");
		} catch (DatabaseException e){
			e.getCause();
		}

		responseObserver.onNext(buildACKresponse(messageHandler, "hmac"));
		responseObserver.onCompleted();
	}

	@Override
	public void postGeneral(Contract.PostRequest request, StreamObserver<Contract.ACK> responseObserver) {
		if(debug != 0) System.out.println("[SERVER] PostGeneral request from client.\n");

		/* Verify request */
		byte[] postBytes = verifyPostRequest(request, responseObserver);

		/* In case the request is faulty */
		if(postBytes == null){
			return;
		}

		PublicKey userKey = SerializationUtils.deserialize(request.getPublicKey().toByteArray());
		String[] announcements = SerializationUtils.deserialize(request.getAnnouncements().toByteArray());

		MessageHandler messageHandler = clientSessions.get(userKey);

		/* create post */
		char[] post = new String(postBytes, StandardCharsets.UTF_8).toCharArray();

		int announcementID = addCounter();
		Announcement announcement = new Announcement(post, userKey, announcements, announcementID, request.getMessageSignature().toByteArray());
		
		synchronized(this) {
			this.generalBoard.add(announcement);
		}
		this.announcementIDs.put(announcementID, announcement);

		/* Save posts */
		try{
			save("generalPosts");
		}catch (DatabaseException e){
			e.getCause();
		}

		responseObserver.onNext(buildACKresponse(messageHandler, "hmac"));
		responseObserver.onCompleted();
	}

	@Override
	public void read(Contract.ReadRequest request, StreamObserver<Contract.ReadResponse> responseObserver) {
		byte[] serializedTargetPublicKey = request.getTargetPublicKey().toByteArray();
		byte[] serializedClientPublicKey = request.getClientPublicKey().toByteArray();

		int numPosts = request.getNumber();
		byte[] number = Ints.toByteArray(numPosts);
		byte[] freshness = request.getFreshness().toByteArray();
		byte[] signature = request.getSignature().toByteArray();

		PublicKey targetUserKey = verifyPublicKey(serializedTargetPublicKey, responseObserver, serializedClientPublicKey, freshness, freshness);

		/* Target is valid. Client must be registered. */
		if(targetUserKey == null || !verifyClientIsRegistered(targetUserKey, responseObserver, serializedClientPublicKey, freshness, freshness)){
			return;
		}

		PublicKey clientUserKey = verifyPublicKey(serializedClientPublicKey, responseObserver, serializedClientPublicKey, freshness, freshness);

		/* Client is valid. Client must be registered. */
		if(clientUserKey == null || !verifyClientIsRegistered(clientUserKey, responseObserver, serializedClientPublicKey, freshness, freshness)){
			return;
		}

		MessageHandler messageHandler = clientSessions.get(clientUserKey);

		/* Client is in session. Verify freshness and integrity-signature */
		if(!verifyIsInSession(messageHandler, responseObserver, serializedClientPublicKey, freshness, freshness) || !verifyMessage(messageHandler, responseObserver, Bytes.concat(serializedTargetPublicKey, serializedClientPublicKey, number), signature, serializedClientPublicKey, freshness, freshness)){
			return;
		}

		/* Prepare announcements */
		ArrayList<Announcement> announcementList = this.privateBoard.get(targetUserKey);

		byte[] responseAnnouncements;
		if(numPosts == 0 || numPosts > announcementList.size()){
			responseAnnouncements = SerializationUtils.serialize(announcementList.toArray(new Announcement[0]));
		}
		else{
			List<Announcement> toSend =  announcementList.subList(announcementList.size() - numPosts, announcementList.size());
			Announcement[] announcements = toSend.toArray(new Announcement[0]);

			responseAnnouncements = SerializationUtils.serialize(announcements);
		}


		responseObserver.onNext(buildReadResponse(messageHandler, responseAnnouncements));
		responseObserver.onCompleted();
	}

	@Override
	public void readGeneral(Contract.ReadRequest request, StreamObserver<Contract.ReadResponse> responseObserver) {
		byte[] serializedClientPublicKey = request.getClientPublicKey().toByteArray();
		int numPosts = request.getNumber();
		byte[] number = Ints.toByteArray(numPosts);
		byte[] freshness = request.getFreshness().toByteArray();
		byte[] signature = request.getSignature().toByteArray();

		PublicKey clientUserKey = verifyPublicKey(serializedClientPublicKey, responseObserver, serializedClientPublicKey, freshness, freshness);

		/* Client is valid. Client must be registered. */
		if(clientUserKey == null || !verifyClientIsRegistered(clientUserKey, responseObserver, serializedClientPublicKey, freshness, freshness)){
			return;
		}

		MessageHandler messageHandler = clientSessions.get(clientUserKey);

		/* Client is in session. Verify freshness and integrity-signature */
		if(!verifyIsInSession(messageHandler, responseObserver, serializedClientPublicKey, freshness, freshness) || !verifyMessage(messageHandler, responseObserver, Bytes.concat(serializedClientPublicKey, number), signature, serializedClientPublicKey, freshness, freshness)){
			return;
		}

		/* Prepare announcements */
		byte[] responseAnnouncements;

		if(numPosts == 0 || numPosts > this.generalBoard.size()){
			responseAnnouncements = SerializationUtils.serialize(this.generalBoard.toArray(new Announcement[0]));
		}
		else{
			List<Announcement> toSent =  this.generalBoard.subList(this.generalBoard.size() - numPosts, this.generalBoard.size());
			responseAnnouncements = SerializationUtils.serialize(toSent.toArray(new Announcement[0]));
		}

		responseObserver.onNext(buildReadResponse(messageHandler, responseAnnouncements));
		responseObserver.onCompleted();
	}

	private synchronized void save(String file) throws DatabaseException{
		try {

			FileOutputStream myWriter = new FileOutputStream(this.databasePath + "/" + file + "_try.txt");

			/* write in file */
			switch (file) {
				case "posts":
						myWriter.write(SerializationUtils.serialize(privateBoard));
					break;
				case "generalPosts":
						myWriter.write(SerializationUtils.serialize(generalBoard));
					break;
			}
			myWriter.close();

			/* File successfully created, transferring to official file */
			Path src = Paths.get(this.databasePath + "/" + file + "_try.txt");
			Path dst = Paths.get(this.databasePath + "/" + file + ".txt");

			Files.move(src, dst, StandardCopyOption.ATOMIC_MOVE);
			//Saves the IDs persistently
			saveIDs();
		} catch (IOException e) {
			throw new DatabaseException("Unable to save: " + e.getMessage());
		}

	}

	private void saveIDs() throws DatabaseException{
		try {
			FileOutputStream myWriter = new FileOutputStream(this.databasePath + "/announcementsID_try.txt");
			myWriter.write(SerializationUtils.serialize(this.announcementIDs));
			myWriter.close();

			/* File successfully created, transferring to official file */
			Path src = Paths.get(this.databasePath + "/announcementsID_try.txt");
			Path dst = Paths.get(this.databasePath + "/announcementsID.txt");

			Files.move(src, dst, StandardCopyOption.ATOMIC_MOVE);

		} catch (IOException e) {
			throw new DatabaseException("Unable to save: " + e.getMessage());
		}


	}

	private synchronized void load() throws DatabaseException{
		try {
			if (new File(this.databasePath + "/posts.txt").exists()) {
				/* read from file posts */
				FileInputStream myReader = new FileInputStream(this.databasePath + "/posts.txt");
				this.privateBoard = SerializationUtils.deserialize(myReader.readAllBytes());
				for(PublicKey key: this.privateBoard.keySet()){
					this.clientSessions.put(key, new MessageHandler(null));
				}
				myReader.close();
			}
			if (new File(this.databasePath + "/generalPosts.txt").exists()) {
				/* read from file generalPosts */
				FileInputStream myReader = new FileInputStream(this.databasePath + "/generalPosts.txt");
				this.generalBoard = SerializationUtils.deserialize(myReader.readAllBytes());
				myReader.close();
			}
			if(new File(this.databasePath + "/announcementsID.txt").exists()) {
				/* read from file generalPosts */
				FileInputStream myReader = new FileInputStream(this.databasePath + "/announcementsID.txt");
				this.announcementIDs = SerializationUtils.deserialize(myReader.readAllBytes());
				myReader.close();
				this.announcementID = this.announcementIDs.size();
			}


		} catch (IOException e) {
			throw new DatabaseException("Unable to load: " + e.getMessage());
		}
	}

	/************************/
	/** AUXILIAR FUNCTIONS **/
	/************************/

	private byte[] verifyPostRequest(Contract.PostRequest request, StreamObserver<Contract.ACK> responseObserver){
		byte[] serializedPublicKey = request.getPublicKey().toByteArray();
		byte[] encryptedMessage = request.getMessage().toByteArray();
		byte[] messageSignature = request.getMessageSignature().toByteArray();
		byte[] serializedAnnouncements = request.getAnnouncements().toByteArray();
		byte[] freshness = request.getFreshness().toByteArray();
		byte[] signature = request.getSignature().toByteArray();

		/* Obtaining the Public Key of the Client */
		PublicKey userKey = verifyPublicKey(serializedPublicKey, responseObserver, serializedPublicKey, freshness, freshness);
		String[] announcements = verifyAnnouncements(serializedAnnouncements, responseObserver, serializedPublicKey, freshness, freshness);

		/* Public Key is valid. Announcements are valid. Client must be registered. */
		if(userKey == null || announcements == null || !verifyClientIsRegistered(userKey, responseObserver, serializedPublicKey, freshness, freshness)){
			return null;
		}

		MessageHandler messageHandler = clientSessions.get(userKey);

		/* Client is in session. Verify message freshness and integrity-signature. References exists.*/
		if(!verifyIsInSession(messageHandler, responseObserver, serializedPublicKey, freshness, freshness) || !verifyMessage(messageHandler, responseObserver, Bytes.concat(serializedPublicKey, encryptedMessage, messageSignature, serializedAnnouncements), signature, serializedPublicKey, freshness, freshness) || !verifyReferences(announcements, responseObserver, serializedPublicKey, freshness, freshness)){
			return null;
		}

		byte[] serverFreshness = Longs.toByteArray(messageHandler.getFreshness());

		byte[] postBytes = null;
		try {
			Cipher decrypt = Cipher.getInstance("RSA/ECB/PKCS1Padding");
			decrypt.init(Cipher.DECRYPT_MODE, privateKey);
			postBytes = decrypt.doFinal(encryptedMessage);
		} catch (IllegalBlockSizeException | BadPaddingException | NoSuchPaddingException | NoSuchAlgorithmException | InvalidKeyException e) {
			System.out.println("[POST] ERROR - Decrypting -  " + e.getMessage() + "\n");
		}

		/* Verify signature of announcements */
		if(!verifySignature(Bytes.concat(serializedPublicKey, postBytes, serializedAnnouncements), messageSignature, userKey, responseObserver, "AnnouncementSignatureInvalid", serializedPublicKey, freshness, serverFreshness)){
			return null;
		}
		return postBytes;
	}

	private PublicKey verifyPublicKey(byte[] serializedPublicKey, StreamObserver<?> responseObserver, byte[] serializedClientKey, byte[] clientFreshness, byte[] serverFreshness){
		try{
			return SerializationUtils.deserialize(serializedPublicKey);
		}catch(SerializationException e){
			responseObserver.onError(buildException(Status.Code.INVALID_ARGUMENT, "PublicKey", serializedClientKey, clientFreshness, serverFreshness));
			return null;
		}
	}

	private String[] verifyAnnouncements(byte[] serializedAnnouncements, StreamObserver<?> responseObserver, byte[] serializedClientKey, byte[] clientFreshness, byte[] serverFreshness){
		try{
			return SerializationUtils.deserialize(serializedAnnouncements);
		} catch(SerializationException e){
			responseObserver.onError(buildException(Status.Code.INVALID_ARGUMENT, "PublicKey", serializedClientKey, clientFreshness, serverFreshness));
			return null;
		}
	}

	private boolean verifyClientIsRegistered(PublicKey userKey, StreamObserver<?> responseObserver, byte[] serializedClientKey, byte[] clientFreshness, byte[] serverFreshness) {
		if(!this.privateBoard.containsKey(userKey)){
			if(debug != 0) System.out.println("\t ERROR: PERMISSION_DENIED - ClientNotRegistered.\n");
			responseObserver.onError(buildException(Status.Code.PERMISSION_DENIED, "ClientNotRegistered", serializedClientKey, clientFreshness, serverFreshness));
			return false;
		}
		return true;
	}

	private boolean verifyClientIsAlreadyRegistered(PublicKey userKey, StreamObserver<?> responseObserver, byte[] serializedClientKey, byte[] clientFreshness, byte[] serverFreshness){
		if(this.privateBoard.get(userKey) != null){
			if(debug != 0) System.out.println("\t ERROR: PERMISSION_DENIED - ClientAlreadyRegistered.");
			responseObserver.onError(buildException(Status.Code.INVALID_ARGUMENT, "ClientAlreadyRegistered", serializedClientKey, clientFreshness, serverFreshness));
			return true;
		}
		return false;
	}

	private boolean verifyFreshness(MessageHandler messageHandler, StreamObserver<?> responseObserver, byte[] serializedClientKey, byte[] clientFreshness, byte[] serverFreshness){
		try {
			messageHandler.verifyFreshness(Longs.fromByteArray(clientFreshness));
		} catch (MessageNotFreshException e) {
			if(debug != 0) System.out.println("\t ERROR: PERMISSION_DENIED - ClientRequestNotFresh.\n");
			responseObserver.onError(buildException(Status.Code.PERMISSION_DENIED, "ClientRequestNotFresh", serializedClientKey, clientFreshness, serverFreshness));
			return false;
		}
		return true;
	}

	private boolean verifySignature(byte[] message, byte[] clientSignature, PublicKey userKey, StreamObserver<?> responseObserver, String error, byte[] serializedClientKey, byte[] clientFreshness, byte[] serverFreshness){
		if(!SignatureHandler.verifyPublicSignature(message, clientSignature, userKey)){
			if(debug != 0) System.out.println("\t ERROR: PERMISSION_DENIED - " + error + ".\n");
			responseObserver.onError(buildException(Status.Code.PERMISSION_DENIED, error, serializedClientKey, clientFreshness, serverFreshness));
			//AnnouncementSignatureInvalid
			return false;
		}
		return true;
	}

	private boolean verifyIsInSession(MessageHandler messageHandler, StreamObserver<?> responseObserver, byte[] serializedClientKey, byte[] clientFreshness, byte[] serverFreshness){
		if(!messageHandler.isInSession()){
			if(debug != 0) System.out.println("\t ERROR: UNAUTHENTICATED - SessionNotInitiated.");
			responseObserver.onError(buildException(Status.Code.UNAUTHENTICATED, "SessionNotInitiated", serializedClientKey, clientFreshness, serverFreshness));
			return false;
		}
		return true;
	}

	private boolean verifyMessage(MessageHandler messageHandler, StreamObserver<?> responseObserver, byte[] supposedMessage, byte[] signature, byte[] serializedClientKey, byte[] clientFreshness, byte[] serverFreshness){
		try {
			messageHandler.verifyMessage(supposedMessage, Longs.fromByteArray(clientFreshness), signature);
		} catch (SignatureNotValidException e) {
			if(debug != 0) System.out.println("\t ERROR: PERMISSION_DENIED - ClientIntegrityViolation.");
			responseObserver.onError(buildException(Status.Code.PERMISSION_DENIED, "ClientIntegrityViolation", serializedClientKey, clientFreshness, serverFreshness));
			return false;
		} catch (MessageNotFreshException e) {
			if(debug != 0) System.out.println("\t ERROR: PERMISSION_DENIED - ClientRequestNotFresh.");
			responseObserver.onError(buildException(Status.Code.PERMISSION_DENIED, "ClientRequestNotFresh", serializedClientKey, clientFreshness, serverFreshness));
			return false;
		}
		return true;
	}

	private boolean verifyReferences(String[] references, StreamObserver<?> responseObserver, byte[] serializedClientKey, byte[] clientFreshness, byte[] serverFreshness){
		for(String reference: references){
			if(!announcementIDs.containsKey(Integer.valueOf(reference))){
				responseObserver.onError(buildException(Status.Code.INVALID_ARGUMENT, "NonExistentAnnouncementReference", serializedClientKey, clientFreshness, serverFreshness));
				return false;
			}
		}
		return true;
	}

	private StatusRuntimeException buildException(Status.Code code, String description, byte[] serializedClientKey, byte[] clientFreshness, byte[] serverFreshness){
		Status status = Status.fromCode(code).withDescription(description);

		Metadata metadata = new Metadata();

		Metadata.Key<byte[]> clientKey = Metadata.Key.of("clientKey-bin", Metadata.BINARY_BYTE_MARSHALLER);
		Metadata.Key<byte[]> clientFreshnessKey = Metadata.Key.of("clientFreshness-bin", Metadata.BINARY_BYTE_MARSHALLER);
		Metadata.Key<byte[]> serverFreshnessKey = Metadata.Key.of("serverFreshness-bin", Metadata.BINARY_BYTE_MARSHALLER);
		Metadata.Key<byte[]> signatureKey = Metadata.Key.of("signature-bin", Metadata.BINARY_BYTE_MARSHALLER);

		metadata.put(clientKey, serializedClientKey);
		metadata.put(clientFreshnessKey, clientFreshness);
		metadata.put(serverFreshnessKey, serverFreshness);
		metadata.put(signatureKey, SignatureHandler.publicSign(Bytes.concat(Ints.toByteArray(code.value()), description.getBytes(), serializedClientKey, clientFreshness, serverFreshness), this.privateKey));

		return status.asRuntimeException(metadata);
	}

	private synchronized int addCounter(){
		return announcementID++;
	}

	private Contract.ACK buildACKresponse(MessageHandler messageHandler, String typeSignature){

		byte[] freshness = Longs.toByteArray(messageHandler.getFreshness());

		byte[] signature = null;

		if(typeSignature.equals("publicSign")){
			signature = SignatureHandler.publicSign(freshness, this.privateKey);
		}
		if(typeSignature.equals("hmac")){
			signature = messageHandler.sign(new byte[0], freshness);
		}

		return Contract.ACK.newBuilder().setFreshness(ByteString.copyFrom(freshness)).setSignature(ByteString.copyFrom(signature)).build();
	}

	private Contract.ReadResponse buildReadResponse(MessageHandler messageHandler, byte[] responseAnnouncements){
		byte[] responseFreshness = Longs.toByteArray(messageHandler.getFreshness());
		byte[] responseSignature = messageHandler.sign(responseAnnouncements, responseFreshness);

		return Contract.ReadResponse.newBuilder().setAnnouncements(ByteString.copyFrom(responseAnnouncements)).setFreshness(ByteString.copyFrom(responseFreshness)).setSignature(ByteString.copyFrom(responseSignature)).build();

	}

	/***********************/
	/** TESTING FUNCTIONS **/
	/***********************/

	@Override
	public void clientRegisteredState(Contract.RegisterRequest request, StreamObserver<Contract.TestsResponse> responseObserver) {
		PublicKey userKey = SerializationUtils.deserialize(request.getPublicKey().toByteArray());

		boolean isUserRegistered = privateBoard.containsKey(userKey);

		Contract.TestsResponse response = Contract.TestsResponse.newBuilder().setTestResult(isUserRegistered).build();

		responseObserver.onNext(response);
		responseObserver.onCompleted();
	}

	@Override
	public void postState(Contract.PostRequest request, StreamObserver<Contract.TestsResponse> responseObserver) {
		char[] post = new String(request.getMessage().toByteArray()).toCharArray();
		PublicKey userKey = SerializationUtils.deserialize(request.getPublicKey().toByteArray());
		String[] announcements = SerializationUtils.deserialize(request.getAnnouncements().toByteArray());

		Announcement testingAnnouncement = new Announcement(post, userKey, announcements, addCounter(), null);

		Contract.TestsResponse response = Contract.TestsResponse.newBuilder().setTestResult(false).build();

		if(this.privateBoard.get(userKey) == null){
			responseObserver.onNext(response);
			responseObserver.onCompleted();
			return;
		}
		for (Announcement announcement: this.privateBoard.get(userKey)) {
			if(announcement.equals(testingAnnouncement)){
				response = Contract.TestsResponse.newBuilder().setTestResult(true).build();
				break;
			}
		}
		responseObserver.onNext(response);
		responseObserver.onCompleted();
	}

	@Override
	public void postGeneralState(Contract.PostRequest request, StreamObserver<Contract.TestsResponse> responseObserver) {
		char[] post = new String(request.getMessage().toByteArray()).toCharArray();
		PublicKey userKey = SerializationUtils.deserialize(request.getPublicKey().toByteArray());
		String[] announcements = SerializationUtils.deserialize(request.getAnnouncements().toByteArray());

		Announcement testingAnnouncement = new Announcement(post, userKey, announcements, addCounter(), null);

		Contract.TestsResponse response = Contract.TestsResponse.newBuilder().setTestResult(false).build();

		for (Announcement announcement: this.generalBoard) {
			if(announcement.equals(testingAnnouncement)){
				response = Contract.TestsResponse.newBuilder().setTestResult(true).build();
			}
		}

		responseObserver.onNext(response);
		responseObserver.onCompleted();
	}

	@Override
	public void cleanPosts(Empty request, StreamObserver<Empty> responseObserver) {
		this.privateBoard = new ConcurrentHashMap<>();
		this.announcementIDs = new ConcurrentHashMap<>();
		try{
			save("posts");
		}catch (DatabaseException e){
			e.getCause();
		}
		responseObserver.onNext(Empty.newBuilder().build());
		responseObserver.onCompleted();
	}

	@Override
	public void cleanGeneralPosts(Empty request, StreamObserver<Empty> responseObserver) {
		this.generalBoard = new ArrayList<>();
		this.announcementIDs = new ConcurrentHashMap<>();
		try{
			save("generalPosts");
		}catch (DatabaseException e){
			e.getCause();
		}
		responseObserver.onNext(Empty.newBuilder().build());
		responseObserver.onCompleted();
	}

}
