package pt.ulisboa.tecnico.SECDPAS;

/* these are generated by the hello-world-server contract */

import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.util.Scanner;

public class DPASClient {
	private PublicKey publicKey;
	private ClientLibrary lib;
	private PrivateKey privateKey;


	public DPASClient(PublicKey p, PrivateKey privateKey){
		//this.lib = new ClientLibrary();
		this.publicKey = p;
		this.privateKey = privateKey;
	}

	public static void main(String[] args) throws Exception {
/*		System.out.println(DPASClient.class.getSimpleName());

		//Check Arguments
		if(args.length < 1){
			System.err.println("Argument(s) missing!");
		}

		DPASClient client;
		//If we are using CC
		if(Boolean.getBoolean(args[0])){
			System.err.println("CC usage not yet implemented!");
			return;
		}

		else {
			KeyPairGenerator kpg = KeyPairGenerator.getInstance("RSA");
			kpg.initialize(2048);
			KeyPair kp = kpg.genKeyPair();

			client = new DPASClient(kp.getPublic(), kp.getPrivate());
		}

		System.out.println("-----------------------------------------------------");
		System.out.println("-				Client Implementation				-");
		System.out.println("-----------------------------------------------------");
		System.out.println();

		MenuInterface menu = new MenuInterface();

		menu.addOption("Register Client");
		menu.addOption("Post to Private Board");
		menu.addOption("Post to General Board");
		menu.addOption("Read from Private Board");
		menu.addOption("Read from General Board");
		menu.addOption("Exit");

		menu.showMenu();

		String selectedOption;

		do {
			selectedOption = menu.selectOption();

			switch(selectedOption){
				case "Register Client":
					client.RegisterClient();
					break;
				default:
					break;
			}
		} while(!selectedOption.equals("Exit"));
*/
	}
/*
	public void RegisterClient(){
		try{
			this.lib.register(publicKey, privateKey);
		} catch (ClientAlreadyRegisteredException e){
			System.out.println("You are already registered!");
		} catch (InvalidArgumentException e){
			System.out.println("Invalid Public Key!");
		}
	}

	public void PostPrivateBoard(){
		Scanner scanner = new Scanner(System.in);

		String inputString = scanner.nextLine();
	}
*/
}
