package pt.ulisboa.tecnico.SECDPAS;

/* these are generated by the hello-world-server contract */
import SECDPAS.grpc.Contract;
import SECDPAS.grpc.DPASServiceGrpc;

import com.google.protobuf.Empty;

import com.google.protobuf.ByteString;
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import org.apache.commons.lang3.SerializationUtils;

import java.security.PublicKey;

public class ClientLibrary {

	private String host = "localhost";
	private int port = 8080;
	private String target = host + ":" + port;

	private ManagedChannel channel;
	private DPASServiceGrpc.DPASServiceBlockingStub stub;

	public ClientLibrary(String host, int port){
		this.target = host + ":" + port;
		this.channel = ManagedChannelBuilder.forTarget(target).usePlaintext().build();
		this.stub = DPASServiceGrpc.newBlockingStub(channel);
	}

	public ClientLibrary(){
		super();
		this.channel = ManagedChannelBuilder.forTarget(target).usePlaintext().build();
		this.stub = DPASServiceGrpc.newBlockingStub(channel);
	}

	public void register(PublicKey userKey) throws ClientAlreadyRegistredException, InvalidArgumentException{
		checkPublicKey(userKey);

		//Serializes key and changes to ByteString
		ByteString publicKey = ByteString.copyFrom(SerializationUtils.serialize(userKey));
		Contract.RegisterRequest request = Contract.RegisterRequest.newBuilder().setPublicKey(publicKey).build();
		try{
			Empty response = stub.register(request);
		} catch (RuntimeException e){
			throw new ClientAlreadyRegistredException(e.getMessage());
		}
	}

	public void post(PublicKey userKey, char[] message) throws InvalidArgumentException, ClientNotRegistredException{
		checkPublicKey(userKey);
		checkMessage(message);

		post(userKey, message, new Announcement[0]);
	}

	public void post(PublicKey userKey, char[] message, Announcement[] references) throws InvalidArgumentException, ClientNotRegistredException{
		checkPublicKey(userKey);
		checkMessage(message);

		try{
			Empty response = stub.post(getPostRequest(userKey, message, references));
		} catch (RuntimeException e){
			throw new ClientNotRegistredException(e.getMessage());
		}
	}

	public void postGeneral(PublicKey userKey, char[] message) throws InvalidArgumentException, ClientNotRegistredException{
		checkPublicKey(userKey);
		checkMessage(message);

		postGeneral(userKey, message, new Announcement[0]);
	}


	public void postGeneral(PublicKey userKey, char[] message, Announcement[] references) throws InvalidArgumentException, ClientNotRegistredException{
		checkPublicKey(userKey);
		checkMessage(message);

		try{
			Empty response = stub.postGeneral(getPostRequest(userKey, message, references));
		} catch (RuntimeException e){
			throw new ClientNotRegistredException(e.getMessage());
		}
	}

	public Announcement[] read(PublicKey userKey, int number) throws ClientNotRegistredException, InvalidArgumentException{
		checkPublicKey(userKey);
		checkNumber(number);

		ByteString publicKey = ByteString.copyFrom(SerializationUtils.serialize(userKey));
		Contract.ReadRequest request = Contract.ReadRequest.newBuilder().setPublicKey(publicKey).setNumber(number).build();

		try {
			Contract.ReadResponse response = stub.read(request);
			return SerializationUtils.deserialize(response.getAnnouncements().toByteArray());
		} catch (RuntimeException e){
			throw new ClientNotRegistredException(e.getMessage());
		}
	}

	public Announcement[] readGeneral(PublicKey userKey, int number) throws ClientNotRegistredException, InvalidArgumentException{
		checkPublicKey(userKey);
		checkNumber(number);

		ByteString publicKey = ByteString.copyFrom(SerializationUtils.serialize(userKey));
		Contract.ReadRequest request = Contract.ReadRequest.newBuilder().setPublicKey(publicKey).setNumber(number).build();

		try {
			Contract.ReadResponse response = stub.readGeneral(request);
			return SerializationUtils.deserialize(response.getAnnouncements().toByteArray());
		} catch (RuntimeException e){
			throw new ClientNotRegistredException(e.getMessage());
		}
	}

	/*************************/
	/**** AUX FUNCTIONS ******/
	/*************************/

	public Contract.PostRequest getPostRequest(PublicKey userKey, char[] message, Announcement[] references){
		ByteString publicKey = ByteString.copyFrom(SerializationUtils.serialize(userKey));
		String post = new String(message);
		ByteString announcements = ByteString.copyFrom(SerializationUtils.serialize(references));

		return Contract.PostRequest.newBuilder().setPublicKey(publicKey).setMessage(post).setAnnouncements(announcements).build();
	}

	/********************/
	/** TEST FUNCTIONS **/
	/********************/

	public boolean clientRegisteredState(PublicKey userKey){
		ByteString publicKey = ByteString.copyFrom(SerializationUtils.serialize(userKey));
		Contract.RegisterRequest request = Contract.RegisterRequest.newBuilder().setPublicKey(publicKey).build();

		Contract.TestsResponse response = stub.clientRegisteredState(request);

		return response.getTestResult();
	}

	public boolean postState(PublicKey userKey, char[] message, Announcement[] references){
		try{
			checkPublicKey(userKey);
			checkMessage(message);

			Contract.TestsResponse response = stub.postState(getPostRequest(userKey, message, references));
			return response.getTestResult();
		} catch (InvalidArgumentException e){
			return false;
		}
	}

	public boolean postState(PublicKey userKey, char[] message){
		try{
			checkPublicKey(userKey);
			checkMessage(message);

			return postState(userKey, message, new Announcement[0]);
		}catch (InvalidArgumentException e){
			return false;
		}
	}

	public boolean postGeneralState(PublicKey userKey, char[] message, Announcement[] references){
		try{
			checkPublicKey(userKey);
			checkMessage(message);

			Contract.TestsResponse response = stub.postGeneralState(getPostRequest(userKey, message, references));
			return response.getTestResult();
		} catch (InvalidArgumentException e){
			return false;
		}
	}

	public boolean postGeneralState(PublicKey userKey, char[] message){
		try{
			checkPublicKey(userKey);
			checkMessage(message);

			return postGeneralState(userKey, message, new Announcement[0]);
		}catch (InvalidArgumentException e){
			return false;
		}
	}

	/*********************/
	/** CHECK ARGUMENTS **/
	/*********************/

	private void checkPublicKey(PublicKey key) throws InvalidArgumentException{
		if(key == null){
			throw new InvalidArgumentException("Public key can not be null");
		}
	}

	private void checkMessage(char[] message) throws InvalidArgumentException{
		if(message == null){
			throw new InvalidArgumentException("Public key can not be null");
		}
		if(message.length > 255) {
			throw new InvalidArgumentException("Post too long, must be smaller than 256 chars");
		}
	}

	private void checkNumber(int n) throws InvalidArgumentException{
		if(n < 0){
			throw new InvalidArgumentException("Number can not be negative");
		}
	}


}
